### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/batik/util/XMLConstants

### ISSUE THREAD

**Issue by ichigo-ichie27** [Tezzxamo/demo_activiti#4]
调用生成流程图的api报java.lang.NoClassDefFoundError: org/apache/batik/util/XMLConstants错误，是什么原因造成的，网络上也没找到解决方案

**Comment by Tezzxamo** [comment]
详情搜索NoClassDefFoundError解决方案，不同情况有不同的解决方案。
